### PR TITLE
upgrade jquery version

### PR DESCRIPTION
**Pull request by loulou2u**
replace older version of jquery to patch xss vulnerability

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
A couple questions:
1. should the be pulled from the resource server, instead of being included directly here?
   It looks like there is at least one spot in the code where it does already, maybe that should also be applied else where? https://github.com/uPortal-Project/WebproxyPortlet/blob/2caa339c282d3066416bd4f4d451a7cb504936ae/src/main/webapp/WEB-INF/jsp/gateway.jsp#L25
2. If we do keep it here, will we need to update the URLs like: https://github.com/uPortal-Project/WebproxyPortlet/blob/2caa339c282d3066416bd4f4d451a7cb504936ae/src/main/webapp/WEB-INF/jsp/gatewayNewPage.jsp#L31 to use the new script?

**Comment by loulou2u** [comment]
Yikes, yeah I'm not a fan of the hardcoding. I'll make some adjustments.. Thanks!

**Comment by loulou2u** [comment]
I changed to the latest resource-server version that uses jquery 1.12.4, and updated the references in the jsp files to use the resource path.

**Review by ChristianMurphy — APPROVED** [review]
Thanks!

**Pull request merged**
