### PR TITLE
fix: switched from request get/set attribute to using session for cap…

### PR DESCRIPTION
**Pull request by bjagg**
…turing proxy request during Action Phase.

Some clean up also included.

### CODE REVIEW

**Comment by jonathanmtran** [comment]
Do you have an example use case to test specifically?

I tested with the default Tomcat landing page it it pulls in the content as expected
[webproxy.portlet-definition.txt](https://github.com/uPortal-Project/WebproxyPortlet/files/8930955/webproxy.portlet-definition.txt)

image

**Comment by bjagg** [comment]
I created a test form that I placed in Tomcat's ROOT webapp for testing the posts named test-form.jsp:

```
<!DOCTYPE html>
<html>
  <body>
    <h3>Welcome <% out.print(request.getParameter("fname"));%></h3>
<form action="./test-form.jsp" method="post">
  <label for="fname">First name:</label>
  <input type="text" id="fname" name="fname"><br><br>
  <input type="submit" value="Submit">
</form>
</body>
</html>
```

**Comment by bjagg** [comment]
image

Important fields are Content Location and Whitelis Regex

**Review by jonathanmtran — APPROVED** [review]
Portlet appears to work when tested proxying static HTML content and with the simple form.

**Pull request merged**
